### ISSUE TITLE
The crops of the sloping field does not appear in rviz

### ISSUE THREAD

**Issue by CyrillePierre** [FiraHackathon/hackathon_evaluation#4]
When the robot crush crops in the sloping field, the rviz marker does not appear and the percentage value does not change.

**Comment by ClementCourcelle** [comment]
The collisions were not monitored for the sloping field. Still the markers do not appear everywhere on the field. The issue is with the function [get_neighborhood_](https://github.com/FiraHackathon/hackathon_evaluation/blob/main/src/crop_field.cpp#L132]). The return value is empty most of the time. 
The `z` value of the contact point and the crop positions are too different. Working only with `x` and `y` seems to be good enough for this function but it would only be a workaround.
I feel like maybe the [crop positions](https://github.com/FiraHackathon/hackathon_evaluation/blob/main/data/sloping_field_stem_positions.csv) are written as if the field is a perfect plane ? (inclined but without the bumps)

**Comment by CyrillePierre** [comment]
The function [get_neighborhood_](https://github.com/FiraHackathon/hackathon_evaluation/blob/976b1f7d6a59a126a3d000d24dff48c29af44fc2/src/crop_field.cpp#L132) use 3D distance and the coordinates of crops are also stored in correct 3D coordinates. I don't think the problem comes from here.

**Comment by CyrillePierre** [comment]
The coordinates of crops in sloping field was wrong. It is fixed in ebf62a6442fc9d784f12e44ca948a89b85e4350b.
